### ISSUE TITLE
It it okay to 3D print and sale parts for SFX-100?

### ISSUE THREAD

**Issue by bergstar** [SimFeedback/SimFeedback-AC-Servo#1]
I have a few requests to print and mill parts from this project to customers, who are not able to do the job them self. And one who wants to have extra assurance on investment.
 
And I have 2 questions about the license of this project:

1. Am I allowed to sale printed / manufactured parts based on STL files in this project?
2. Am I allowed to sale complete build actuators according to specifications of the project?

Full disclosure and attribution to the project will be given. And other parts of by-nc-sa/4.0 will be followed.

**Comment by saxxon66** [comment]
No sorry, but this project is for private use only and commercial use is forbidden by the license terms.
You are not allowed to use any of the information to produce or offer any part of this project for sale.

**Comment by samkatakouzinosracing** [comment]
https://opensfx.com/downloads/#licensing  
Is this the license you're referring to?

**Comment by saxxon66** [comment]
https://github.com/SimFeedback/SimFeedback-AC-Servo/wiki/License

**Comment by bergstar** [comment]
@saxxon66 Okay, but is it possible to buy a license to manufacture? If not, the only option will be to re-create the models from ground up - and I would rather avoid that.
